### ISSUE TITLE
Add Feature: Long-Term Sentiment Algorithm

### ISSUE THREAD

**Issue by summercms** [chartingshow/documentation#106]
## Enhancement idea

- [x] Add Feature: Long-Term Sentiment Algorithm.
- [x] Connect to Alerts Modules and add custom alerts, see here: https://github.com/chartingshow/documentation/issues/70
- [x] Connect to warning signals module, see here: https://github.com/chartingshow/documentation/issues/267
- [x] Connect to Trading Signals module, see here: https://github.com/chartingshow/documentation/issues/269
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194

## Description

The long-term sentiment algorithm is made up of several sections.

The first section uses blockchain data and not price action to work out whether the cryptocurrency market is in either a `bull run` or a `bear market`.

The next section then divides the `bull run` into various stages. The primary stage is `Bitcoin` making gains during the bull run. A secondary stage is when `Bitcoin` and the `Altcoins` are making gains. An extra stage can check the current trading cryptoasset to see if it can make gains during the primary stage when `Bitcoin` and **not the Altcoins** are making gains! This happens when the `Altcoin` is trending and there is high interest in the cryptoasset.

### Trading Strategy

During a `bear market` traders should hold stable coins and either not trade the market or get in and out quickly!

During a `bull run` traders should hold `Bitcoin` and switch to `Altcoins` during the secondary stage or in special cases the extra stage when the `Altcoin` is trending.

The trading strategy will be shown in the data window on the chart in real-time!

### Data Window Results

- Bear Market ▼ (Hold Stable Coins)
- Bull Market ▲ (Bitcoin Only)
- Bull Market ▲ (Bitcoin + Current Asset)
- Bull Market ▲ (Bitcoin + Altcoins)

(*) - The `Bull Market ▲ (Bitcoin + Current Asset)` result is added to the core code and not to the `crypto market` algorithm.

## Links

https://www.investopedia.com/insights/digging-deeper-bull-and-bear-markets/
