### ISSUE TITLE
Add Feature: Medium-Term Sentiment Algorithm

### ISSUE THREAD

**Issue by summercms** [chartingshow/documentation#117]
## Enhancement idea

- [x] Add Feature: Medium-Term Sentiment Algorithm.
- [x] Connect Algorithm to Trend Analysis Model 1 + 2 Algorithms.
- [x] Add options in settings to choose between Trend Analysis Model 1 + 2 Algorithms.
- [x] Add background highlighting.
- [x] Connect to Alerts Modules and add custom alerts, see here: https://github.com/chartingshow/documentation/issues/70
- [x] Connect to warning signals module, see here: https://github.com/chartingshow/documentation/issues/267
- [x] Connect to Trading Signals module, see here: https://github.com/chartingshow/documentation/issues/269
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194
- [x] Add dark and Light mode options.
- [x] Add to data window.

## Description

n/a

## Links

n/a
