### ISSUE TITLE
Add Feature: Bull-Bear Power (BBP) algorithm

### ISSUE THREAD

**Issue by summercms** [chartingshow/documentation#130]
## Enhancement idea

- [x] Add Feature: Bull-Bear Power (BBP) algorithm.
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194
- [x] Add to data window.
- [x] Update Doc's.
- [x] Connect to Alerts Modules and add custom alerts, see here: https://github.com/chartingshow/documentation/issues/70
- [x] Connect to warning signals module, see here: https://github.com/chartingshow/documentation/issues/267
- [x] Connect to Trading Signals module, see here: https://github.com/chartingshow/documentation/issues/269
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194
- [x] Add some basic tests to the `Tests` section, see here: https://github.com/chartingshow/documentation/tree/master/trading/tests/bull-and-bear-power

## Description

The Bull-Bear Power (BBP) algorithm, otherwise known as the Elder-Ray Index, estimates the relationship between the strength of bulls (buyers) and bears (sellers) on an instrument. When the algorithm's value is nonzero, it supposedly suggests that either bulls or bears have more power in the market. The greater the distance is from zero, the greater the apparent dominance of bulls or bears. Positive values indicate higher bull power and negative values indicate higher bear power.

The logic is simple: the market situation is constantly changing as bears turn into bulls and vice versa. The indicators help to track this conversion and trade on it.

## Links

n/a

**Comment by summercms** [comment]
Four Modules (to code):

- Bull Power
- Bear Power
- Bull-Bear Power (Histogram)
- Bull-Bear Trend (Net - Trendline)

**Comment by summercms** [comment]
Warning Signals:

Crossing +2 or -2 (out of sideways range).

**Comment by summercms** [comment]
Tests complete: Coding can start now!
