### ISSUE TITLE
Add Feature: Stablecoin Flows Algorithm

### ISSUE THREAD

**Issue by summercms** [chartingshow/documentation#14]
## Enhancement idea

- [x] Add Feature: Stablecoin Flows Algorithm.
- [x] Add dynamic timeframe to calculations.
- [x] Add to data window.
- [x] Update Doc's.
- [x] Connect to Alerts Modules and add custom alerts, see here: https://github.com/chartingshow/documentation/issues/70
- [x] Connect to warning signals module, see here: https://github.com/chartingshow/documentation/issues/267
- [x] Connect to Trading Signals module, see here: https://github.com/chartingshow/documentation/issues/269
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194

## Description

The algorithm looks at the movements of Stablecoins and calculates the net money flow.

`Inflows` are defined when Stablecoins deposited into the exchange wallets are more than Stablecoin withdrawal from the exchange wallets, this is a `bearish` trading signal.

`Outflows` are defined when Stablecoins withdrawn from the exchange wallets are more than Stablecoin deposited into the exchange wallets, this is a `bullish` trading signal.

## Links

https://www.investopedia.com/terms/s/stablecoin.asp

https://www.bankofengland.co.uk/explainers/what-are-stablecoins-and-how-do-they-work

https://en.wikipedia.org/wiki/Stablecoin

**Comment by summercms** [comment]
set to D1 ?

**Comment by summercms** [comment]
Running Tests (H1 - H4)

**Comment by summercms** [comment]
Merge to `Core` code and `Crypto Market` algorithms.
