### ISSUE TITLE
Add Feature: Fast and Slow Bands Algorithm

### ISSUE THREAD

**Issue by summercms** [chartingshow/documentation#152]
## Enhancement idea

- [x] Add Feature: Fast and Slow Bands Algorithm.
- [x] Set default values from tests.
- [x] Add option to select different types of moving averages.
- [x] Connect the moving average algorithm.
- [x] Re-design the menu options.
- [x] Code slow multiplier equations.
- [x] Add trend band colours.
- [x] Update the doc's.
- [x] Update candlestick colouring themes to include: `Slow Band` and `Fast Band` settings.
- [x] Connect to Alerts Modules and add custom alerts, see here: https://github.com/chartingshow/documentation/issues/70
- [x] Connect to warning signals module, see here: https://github.com/chartingshow/documentation/issues/267
- [x] Connect to Trading Signals module, see here: https://github.com/chartingshow/documentation/issues/269
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194
- [x] Connect to the Moving Average and Custom Filter algorithm, see here: https://github.com/chartingshow/documentation/issues/183

## Description

The Fast and Slow Bands algorithm is momentum based to determine price trends and sideways consolidation periods.

This is a trend following algorithm that uses a fast band to capture near-term and short-term price swings and a slow band to capture pullback areas and reversal signals for short-term and medium-term price action.

The Fast and Slow Bands algorithm is connected to the "Moving Average and Custom Filter" algorithm, where traders can setup many different conditions to tailor better price action signals.

This algorithm is not intended to replace the Trend Analysis Model 1 and 2 algorithms. But instead to work side by side and extend the visual trend results by filling in the gaps left by Trend Analysis Models to better help traders determine the stages of the trend. For example, highlighting pullback areas, confirming reversals, failed low/high swing points, range support and resistances and many more useful features.

## Links

https://www.investopedia.com/terms/m/movingaverage.asp

**Comment by summercms** [comment]
Update crypto market algo and Core algo codes as well.

**Comment by summercms** [comment]
Close down: `Variable Median Area` algorithm.

**Comment by summercms** [comment]
Trend background colour.

**Comment by summercms** [comment]
QQE or Qualitative Quantitative Estimation

**Comment by summercms** [comment]
Warning Signals: Fast Ok - Slow - Issues (when testing)

**Comment by summercms** [comment]
Pullback Notes and Tests for Up Leg Move

**Comment by summercms** [comment]
Swing Labels only show when High-Low algo is turned on.

**Comment by summercms** [comment]
Update doc's <<<<<<<<<<<<<

**Comment by summercms** [comment]
themes <<<<<<<
