### ISSUE TITLE
Add Feature: Nadaraya-Watson (Kernel Regression) Bands Algorithm

### ISSUE THREAD

**Issue by summercms** [chartingshow/documentation#174]
## Enhancement idea

- [x] Add Feature: Nadaraya-Watson (Kernel Regression) Bands Algorithm.
- [x] Connect to Alerts Modules and add custom alerts, see here: https://github.com/chartingshow/documentation/issues/70
- [x] Add Settings.
- [x] Update Doc's.
- [x] Connect to warning signals module, see here: https://github.com/chartingshow/documentation/issues/267
- [x] Add some basic tests to the `Tests` section, see here: https://github.com/chartingshow/documentation/blob/master/trading/tests/nadaraya-watson-kernel-regression-bands.ipynb
- [x] Re-coded a non-repainting method for better performance.
- [x] Connect to Trading Signals module, see here: https://github.com/chartingshow/documentation/issues/269
- [x] Add options to settings menu.
- [x] Allow traders to adjust Standard Deviation of each band in the settings menu.
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194

## Description

The statistical techniques for regression function estimation that were created by G. S. Watson and E. A. Nadaraya in the 1960's are the foundation of the Nadaraya-Watson Envelope algorithm. The Nadaraya-Watson Envelope method and other trading tools were developed as a result of the kernel regression ideas they established, despite the fact that their work was not expressly focused on developing trading algorithms.

Traders and programmers have developed trading algorithms that use historical price data to assess market patterns, spot possible reversals, and offer insights into price movements over time by using statistical techniques like kernel regression. The Nadaraya-Watson Envelope algorithm, which provides a non-repainting envelope based on Kernel Smoothing to outline market extremes and support technical analysis in trading strategies, has grown to be a useful tool for traders looking for precise and trustworthy insights into market trends and price dynamics.

By employing a kernel regression technique to smooth price data, the Nadaraya-Watson Envelope algorithm is a dynamic volatility algorithm that adjusts to shifting market conditions. To give limits for excessive price swings, it computes upper and lower bounds using the Average True Range (ATR) and certain variables.

By examining the link between price and envelopes, this technique is intended to assist traders in locating possible reversal zones and verifying the trend's direction.

## Links

https://en.wikipedia.org/wiki/Kernel_regression

https://www.cs.toronto.edu/~duvenaud/cookbook/

**Comment by summercms** [comment]
Merge to `Core` code and `Crypto Market` algorithms.
