### ISSUE TITLE
Add Feature: Semaphore Signal Level (SSL) Algorithm

### ISSUE THREAD

**Issue by summercms** [chartingshow/documentation#197]
## Enhancement idea

- [x] Add Feature: Semaphore Signal Level (SSL) Algorithm.
- [x] Connect to Alerts Modules and add custom alerts, see here: https://github.com/chartingshow/documentation/issues/70
- [x] Connect to warning signals module, see here: https://github.com/chartingshow/documentation/issues/267
- [x] Connect to Trading Signals module, see here: https://github.com/chartingshow/documentation/issues/269
- [x] Add Settings.
- [x] Add to data window.
- [x] Update Doc's.
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194
- [x] Connect to the Moving Average and Custom Filter algorithm, see here: https://github.com/chartingshow/documentation/issues/183

## Description

The Semaphore Signal Level (SSL) algorithm combines moving averages to provide you with a clear visual signal of near-term price movement dynamic. It's designed to show you all the price action pivot swing points. The algorithm has been modified to connect to the Moving Average and Custom Filter algorithm, to give traders the most amount of options and customizations.

This algorithm creates an envelope curve that tracks the market price by applying two moving averages, one to the price high and the other to the price low. Trading on the flip technique-where price goes from above the two moving averages to below them and vice versa-is the rationale behind this strategy.

The algorithm indicates that the direction of price movement is changing or likely to shift (from long to short or from short to long) when the two moving averages meet.

## Links

n/a

**Comment by summercms** [comment]
Merge to `Core` code and `Crypto Market` algorithms.

**Comment by summercms** [comment]
Alert Conditions <<<

**Comment by summercms** [comment]
Connect to Trading Signals Module. <<<<<
