### ISSUE TITLE
Add Feature: Big Move Gauge Algorithm

### ISSUE THREAD

**Issue by summercms** [chartingshow/documentation#72]
## Enhancement idea

- [x] Add Feature: Big Move Gauge Algorithm.
- [x] Connect to Alerts Modules and add custom alerts, see here: https://github.com/chartingshow/documentation/issues/70
- [x] Connect to warning signals module, see here: https://github.com/chartingshow/documentation/issues/267
- [x] Connect to Trading Signals module, see here: https://github.com/chartingshow/documentation/issues/269
- [x] Add to Themes, see here: https://github.com/chartingshow/documentation/issues/194
- [x] Add to data window.
- [x] Update Doc's.

## Notes

> Renamed from **Big Move Indicator** into **Big Move Gauge** to avoid confusion as it's a trading algorithm and not a trading indicator.

**Fast** = uses the Trend Analysis Model 2 algorithm with a setting of `10.0` which is quicker than Trend Analysis Model 1 default setting.

**Slow** = uses the Trend Analysis Model 1 algorithm with the default settings.

## Description

The big move gauge algorithm uses the daily calculations of volatility and time-weighted average prices (TWAP) calculated by taking price measurements at 1 minute intervals from the Bitcoin vs the US Dollar price. The `fast` setting uses a 24-hour H1 timeframe setting and the `slow` setting uses a rolling 7-day H4 timeframe setting.

The `fast` setting shows all the smaller individual moves and traders can look at each move to tell if the bulls or bears are in-control of the price action at that exact period. Traders can also use the `fast` setting to confirm U-Shape and V-Shape pattern moves. Traders can also use the `fast` setting to confirm lower-timeframe breakouts. The `fast` module uses the Trend Analysis Model 2 algorithm with a setting of `10.0` which is quicker than Trend Analysis Model 1 default setting.

The `slow` setting shows all the longer trend moves and traders can use this to confirm breakouts and when the momentum for the trend is over. Traders can also use the `slow` setting to confirm higher-timeframe breakouts. The `slow` module uses the Trend Analysis Model 1 algorithm with the default settings.

## Links

https://en.wikipedia.org/wiki/Time-weighted_average_price

https://www.investopedia.com/terms/v/volatility.asp

**Comment by summercms** [comment]
https://www.tradingview.com/support/solutions/43000653369-how-are-hange-and-hange-calculated-in-the-watchlist/

**Comment by summercms** [comment]
Clean up Trend Analysis Model 1/2 connections

**Comment by summercms** [comment]
- Add real-time Updates to data window.

**Comment by summercms** [comment]
- `fast` and `slow` are delayed

- `slow` seems to be delayed a lot more though....?
